ARG org=igot-rog
ARG build_tag=latest

FROM $org/ui-spv-igot:$build_tag

WORKDIR /app/dist
COPY SPV/client-assets/dist www/en/assets
RUN npm install --production
EXPOSE 3004

CMD [ "npm", "run", "serve:prod" ]
